// Source snapshot reviewed 4 September 2026. No affiliation or endorsement implied.
export const SOURCES = [
  { href: "https://www.clinicalestablishments.mohfw.gov.in/sites/default/files/standard-treatment-guidelines/5191.pdf#page=124", en: "MoHFW — Screening, Diagnosis, Assessment, and Management of Primary Hypertension (2016), Annexure 2, p. 124: Indian BMI and waist references", bn: "MoHFW — উচ্চ রক্তচাপের স্ক্রিনিং, নির্ণয়, মূল্যায়ন ও ব্যবস্থাপনা (২০১৬), পরিশিষ্ট ২, পৃ. ১২৪: ভারতীয় BMI ও কোমরের মাপ" },
  { href: "https://www.who.int/data/nutrition/nlis/info/malnutrition-in-women", en: "WHO — Adult BMI classification (Nutrition Landscape Information System)", bn: "WHO — প্রাপ্তবয়স্কদের BMI শ্রেণিবিভাগ (পুষ্টি তথ্যব্যবস্থা)" },
  { href: "https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight", en: "WHO — Obesity and overweight: BMI, limitations and health risks", bn: "WHO — স্থূলতা ও অতিরিক্ত ওজন: BMI, সীমাবদ্ধতা ও স্বাস্থ্যঝুঁকি" },
  { href: "https://www.who.int/europe/news-room/fact-sheets/item/physical-activity", en: "WHO — Physical activity recommendations for adults", bn: "WHO — প্রাপ্তবয়স্কদের শারীরিক পরিশ্রমের পরামর্শ" },
];

export const COPY = {
  en: {
    language: "Language selection", home: "Worklity home", eyebrow: "ADULT HEALTH AWARENESS", title: "BMI Calculator India",
    intro: "Check your BMI from height and weight, with Indian and WHO references. For adults aged 18 and above only.",
    caution: "Not for children or pregnancy. BMI cannot distinguish muscle from body fat; illness, body composition and other factors can affect its usefulness. Discuss individual interpretation with a healthcare professional.",
    formTitle: "Your measurements", age: "Age (completed years)", sex: "Sex", select: "Select", male: "Male", female: "Female",
    sexNote: "Sex is used only for the optional waist reference. It does not change the BMI formula or adult BMI bands.",
    heightUnit: "Height unit", cm: "Centimetres (cm)", ft: "Feet + inches", heightCm: "Height (cm)", feet: "Feet", inches: "Inches", weight: "Weight (kg)", waist: "Waist circumference (cm)", optional: "Optional", inchesNote: "Enter whole feet and inches from 0 to less than 12.",
    waistHelp: "Measure midway between your lowest rib and the top of your hip bone after a normal breath out, without tightening the tape. Ask a health professional if unsure.",
    calculate: "Calculate BMI", reset: "Reset", limits: "Calculator input limits (not healthy ranges): age 18–120 whole years, height 50–275 cm, weight 10–650 kg, optional waist 40–250 cm. Measurements outside these limits need individual assessment.",
    privacy: "Your entries stay in this page’s memory and are not saved by this calculator.",
    result: "Your BMI", india: "Indian / Asian-Indian risk interpretation", screening: "A screening category, not a diagnosis.",
    rounding: "BMI is shown to one decimal place. Categories use the unrounded value, so a rounded number near a boundary can appear in the neighbouring range.",
    categories: { UNDERWEIGHT: "Underweight", NORMAL: "Normal range", OVERWEIGHT: "Overweight range", OBESITY: "Obesity range" },
    yourRange: "Your range", heightSummary: "Height", weightSummary: "Weight", waistSummary: "Optional waist reference",
    waistHigh: "At or above the cited waist reference. This may add information about cardiometabolic risk even with a normal BMI; discuss it with a healthcare professional. It is not a diagnosis.",
    waistBelow: "Below the cited waist reference. This does not rule out health risks or replace routine health checks.",
    waistRef: "The cited MoHFW guideline recommends waist measurements below 90 cm for men and below 80 cm for women. Waist does not change your BMI category.",
    guidanceTitle: "NCD Health Guidance", ncdMeaning: "NCD means noncommunicable disease. These prompts support awareness, not disease prediction.",
    guidance: {
      UNDERWEIGHT: "Your BMI is below the adult reference range. Focus on balanced nutrition, not weight-loss advice. A qualified professional can assess low weight, especially if it is unintentional or changing.",
      MAINTAIN: "Your BMI is in the Indian reference range. Maintain balanced meals and regular activity, avoid tobacco, and arrange routine health checks as appropriate. A normal BMI does not mean zero NCD risk.",
      ELEVATED: "Higher BMI and excess body weight are associated with higher risk of high blood pressure, type 2 diabetes and cardiovascular disease. This result does not diagnose any of them. Discuss your measurements and health history with a qualified healthcare professional.",
    },
    prompts: ["Know your blood pressure; ask when it should be checked.", "Ask whether a blood glucose check is appropriate for you.", "Choose a balanced diet and regular activity suited to your health.", "Avoid tobacco; ask for support if you want to stop."],
    activity: "General WHO adult guidance: 150–300 minutes of moderate-intensity aerobic activity per week. Adapt activity to your ability and health conditions; seek individual advice when needed.",
    who: "WHO International Reference", whoIntro: "The international reference uses different thresholds: overweight starts at 25 and obesity at 30. The Indian reference above uses 23 and 25. These are distinct screening references, not competing diagnoses.",
    whoRows: ["Underweight: below 18.5", "Normal range: 18.5 to below 25", "Overweight: 25 or above (includes obesity)", "Obesity: 30 or above"],
    whoResult: "Your WHO reference category", formulaTitle: "How BMI is calculated", formula: "BMI = weight (kg) ÷ [height (m) × height (m)]. Centimetres are divided by 100; one inch equals 2.54 cm and one foot equals 12 inches.",
    example: "Example: 65 kg and 170 cm gives BMI 22.5, within both reference normal ranges. Age confirms adult use; it does not alter the formula.",
    checkTitle: "Know Your NCD Risk", checkIntro: "Optional reflection — mark topics to discuss or follow up. This is not a clinical score; your selections do not change the result or estimate disease probability.",
    checks: ["Blood pressure checked recently?", "Blood glucose checked recently?", "Any tobacco use?", "Regular physical activity?"],
    faqTitle: "Frequently asked questions", faqs: [
      ["Why are Indian and WHO results different?", "This page uses the cited MoHFW Indian thresholds for its main interpretation and shows the WHO international thresholds separately. Use a professional assessment for personal decisions."],
      ["Can someone under 18 use this calculator?", "No. Children and adolescents require age-appropriate growth assessment, not these adult categories."],
      ["Does a high BMI mean I have diabetes or heart disease?", "No. BMI is a screening measure. Blood pressure, tests, health history and professional assessment provide different information."],
      ["Is waist measurement required?", "No. You can calculate BMI without it. If supplied, it adds a separate waist reference, not a disease diagnosis."],
    ],
    sources: "Medical references", sourceNote: "References checked 4 September 2026. Worklity is independent and is not affiliated with or endorsed by WHO, MoHFW, NHM or the Government of India.",
    disclaimer: "This calculator is for informational and health-awareness purposes and does not replace medical advice, diagnosis, or treatment.",
    errors: { ADULTS_ONLY: "This calculator is only for adults aged 18 and above. Do not use adult BMI categories for children or adolescents.", INVALID_AGE: "Enter your completed age as a whole number from 18 to 120.", INVALID_SEX: "Select Male or Female for the waist reference.", INVALID_HEIGHT_UNIT: "Choose cm or feet + inches.", INVALID_HEIGHT: "Enter a valid height from 50 to 275 cm (or its feet/inches equivalent).", INVALID_FEET: "Enter whole feet from 0 to 9, with a valid total height.", INVALID_INCHES: "Enter inches from 0 to less than 12; enter 0 for whole feet.", INVALID_WEIGHT: "Enter a valid weight from 10 to 650 kg.", INVALID_WAIST: "Leave waist blank, or enter a valid measurement from 40 to 250 cm.", INVALID_INPUT: "Check your measurements and enter valid numbers." },
  },
  bn: {
    language: "ভাষা নির্বাচন", home: "Worklity হোম", eyebrow: "প্রাপ্তবয়স্কদের স্বাস্থ্য সচেতনতা", title: "BMI ক্যালকুলেটর — ভারত",
    intro: "উচ্চতা ও ওজন থেকে BMI দেখুন, ভারতীয় ও WHO মানদণ্ডসহ। শুধু ১৮ বছর বা তার বেশি বয়সীদের জন্য।",
    caution: "শিশু বা গর্ভাবস্থার জন্য নয়। BMI পেশি ও শরীরের চর্বি আলাদা করতে পারে না; অসুস্থতা, শরীরের গঠন ও অন্য বিষয় এর উপযোগিতায় প্রভাব ফেলতে পারে। নিজের ফলের ব্যাখ্যা স্বাস্থ্য পেশাজীবীর সঙ্গে আলোচনা করুন।",
    formTitle: "আপনার মাপ", age: "বয়স (পূর্ণ বছর)", sex: "লিঙ্গ", select: "বেছে নিন", male: "পুরুষ", female: "মহিলা",
    sexNote: "লিঙ্গ শুধু ঐচ্ছিক কোমরের মাপের মানদণ্ডে ব্যবহৃত হয়। এতে BMI-এর সূত্র বা প্রাপ্তবয়স্কদের BMI সীমা বদলায় না।",
    heightUnit: "উচ্চতার একক", cm: "সেন্টিমিটার (cm)", ft: "ফুট + ইঞ্চি", heightCm: "উচ্চতা (cm)", feet: "ফুট", inches: "ইঞ্চি", weight: "ওজন (kg)", waist: "কোমরের মাপ (cm)", optional: "ঐচ্ছিক", inchesNote: "পূর্ণ ফুট দিন এবং ইঞ্চি ০ থেকে ১২-এর কম রাখুন।",
    waistHelp: "স্বাভাবিক শ্বাস ছাড়ার পর সবচেয়ে নিচের পাঁজর ও নিতম্বের হাড়ের উপরের অংশের মাঝামাঝি মাপুন। ফিতা টেনে চেপে ধরবেন না। সন্দেহ হলে স্বাস্থ্য পেশাজীবীর সাহায্য নিন।",
    calculate: "BMI হিসাব করুন", reset: "রিসেট", limits: "এই ক্যালকুলেটরের ইনপুট সীমা (স্বাস্থ্যকর মাপের সীমা নয়): বয়স ১৮–১২০ পূর্ণ বছর, উচ্চতা ৫০–২৭৫ cm, ওজন ১০–৬৫০ kg, ঐচ্ছিক কোমর ৪০–২৫০ cm। এর বাইরে হলে ব্যক্তিগত মূল্যায়ন দরকার।",
    privacy: "আপনার তথ্য শুধু এই পেজের মেমরিতে থাকে; এই ক্যালকুলেটর তা সংরক্ষণ করে না।",
    result: "আপনার BMI", india: "ভারতীয় / এশীয়-ভারতীয় ঝুঁকির ব্যাখ্যা", screening: "এটি প্রাথমিক যাচাইয়ের শ্রেণি, রোগ নির্ণয় নয়।",
    rounding: "BMI দশমিকের এক ঘর পর্যন্ত দেখানো হয়। শ্রেণি নির্ধারণে দশমিক ছোট করার আগের আসল মান ব্যবহার করা হয়। তাই সীমার কাছাকাছি দেখানো সংখ্যা পাশের শ্রেণির মতো মনে হতে পারে।",
    categories: { UNDERWEIGHT: "কম ওজন", NORMAL: "স্বাভাবিক সীমা", OVERWEIGHT: "অতিরিক্ত ওজনের সীমা", OBESITY: "স্থূলতার সীমা" },
    yourRange: "আপনার সীমা", heightSummary: "উচ্চতা", weightSummary: "ওজন", waistSummary: "ঐচ্ছিক কোমরের মানদণ্ড",
    waistHigh: "কোমরের মাপ উল্লিখিত সীমায় বা তার উপরে। BMI স্বাভাবিক হলেও এটি হৃদ্‌স্বাস্থ্য ও বিপাকীয় ঝুঁকি সম্পর্কে অতিরিক্ত তথ্য দিতে পারে। স্বাস্থ্য পেশাজীবীর সঙ্গে আলোচনা করুন। এটি রোগ নির্ণয় নয়।",
    waistBelow: "কোমরের মাপ উল্লিখিত সীমার নিচে। এর অর্থ স্বাস্থ্যঝুঁকি নেই এমন নয়, আর এটি নিয়মিত স্বাস্থ্য পরীক্ষার বিকল্প নয়।",
    waistRef: "উল্লিখিত MoHFW নির্দেশিকায় পুরুষদের কোমর ৯০ cm-এর নিচে ও মহিলাদের ৮০ cm-এর নিচে রাখার মানদণ্ড দেওয়া আছে। কোমরের মাপ আপনার BMI শ্রেণি বদলায় না।",
    guidanceTitle: "NCD স্বাস্থ্য পরামর্শ", ncdMeaning: "NCD মানে অসংক্রামক রোগ। এই কথাগুলো সচেতনতার জন্য, রোগের পূর্বাভাস নয়।",
    guidance: {
      UNDERWEIGHT: "আপনার BMI প্রাপ্তবয়স্কদের মানদণ্ডের নিচে। ওজন কমানোর বদলে সুষম পুষ্টিতে মন দিন। কম ওজন অনিচ্ছাকৃত হলে বা ওজন বদলাতে থাকলে যোগ্য স্বাস্থ্য পেশাজীবীর মূল্যায়ন নিন।",
      MAINTAIN: "আপনার BMI ভারতীয় মানদণ্ডের স্বাভাবিক সীমায়। সুষম খাবার ও নিয়মিত শারীরিক কাজ বজায় রাখুন, তামাক এড়িয়ে চলুন এবং প্রয়োজনমতো স্বাস্থ্য পরীক্ষা করান। স্বাভাবিক BMI মানে NCD ঝুঁকি শূন্য নয়।",
      ELEVATED: "বেশি BMI ও অতিরিক্ত ওজনের সঙ্গে উচ্চ রক্তচাপ, টাইপ ২ ডায়াবেটিস ও হৃদ্‌রোগের বেশি ঝুঁকির সম্পর্ক আছে। এই ফল দিয়ে কোনো রোগ নির্ণয় হয় না। আপনার মাপ ও স্বাস্থ্যের ইতিহাস যোগ্য স্বাস্থ্য পেশাজীবীর সঙ্গে আলোচনা করুন।",
    },
    prompts: ["নিজের রক্তচাপ জানুন; কখন পরীক্ষা দরকার জিজ্ঞাসা করুন।", "আপনার রক্তে শর্করা পরীক্ষা দরকার কি না জেনে নিন।", "স্বাস্থ্য অনুযায়ী সুষম খাবার ও নিয়মিত শারীরিক কাজ বেছে নিন।", "তামাক এড়িয়ে চলুন; ছাড়তে চাইলে সাহায্য নিন।"],
    activity: "WHO-এর সাধারণ প্রাপ্তবয়স্কদের পরামর্শ: সপ্তাহে ১৫০–৩০০ মিনিট মাঝারি মাত্রার অ্যারোবিক শারীরিক কাজ। নিজের সামর্থ্য ও স্বাস্থ্য অনুযায়ী করুন; প্রয়োজনে ব্যক্তিগত পরামর্শ নিন।",
    who: "WHO আন্তর্জাতিক মানদণ্ড", whoIntro: "আন্তর্জাতিক মানদণ্ডে অতিরিক্ত ওজন শুরু হয় ২৫ থেকে, স্থূলতা ৩০ থেকে। উপরের ভারতীয় মানদণ্ডে সীমা যথাক্রমে ২৩ ও ২৫। এগুলো আলাদা প্রাথমিক যাচাইয়ের মানদণ্ড, রোগ নির্ণয় নয়।",
    whoRows: ["কম ওজন: ১৮.৫-এর নিচে", "স্বাভাবিক সীমা: ১৮.৫ থেকে ২৫-এর কম", "অতিরিক্ত ওজন: ২৫ বা বেশি (স্থূলতাও অন্তর্ভুক্ত)", "স্থূলতা: ৩০ বা বেশি"],
    whoResult: "WHO মানদণ্ডে আপনার শ্রেণি", formulaTitle: "BMI কীভাবে হিসাব হয়", formula: "BMI = ওজন (kg) ÷ [উচ্চতা (m) × উচ্চতা (m)]। সেন্টিমিটারকে ১০০ দিয়ে ভাগ করা হয়; ১ ইঞ্চি = ২.৫৪ cm এবং ১ ফুট = ১২ ইঞ্চি।",
    example: "উদাহরণ: ৬৫ kg ও ১৭০ cm হলে BMI ২২.৫, যা দুই মানদণ্ডেই স্বাভাবিক সীমায়। বয়স শুধু প্রাপ্তবয়স্ক ব্যবহার নিশ্চিত করে; সূত্র বদলায় না।",
    checkTitle: "আপনার NCD ঝুঁকি সম্পর্কে জানুন", checkIntro: "ঐচ্ছিকভাবে ভাবুন — যে বিষয়গুলো নিয়ে কথা বলতে বা খোঁজ নিতে চান, চিহ্ন দিন। এটি চিকিৎসাগত স্কোর নয়; আপনার নির্বাচন ফল বদলায় না বা রোগের সম্ভাবনা হিসাব করে না।",
    checks: ["সম্প্রতি রক্তচাপ পরীক্ষা করেছেন?", "সম্প্রতি রক্তে শর্করা পরীক্ষা করেছেন?", "তামাক ব্যবহার করেন?", "নিয়মিত শারীরিক কাজ করেন?"],
    faqTitle: "সাধারণ প্রশ্ন", faqs: [
      ["ভারতীয় ও WHO ফল আলাদা কেন?", "মূল ব্যাখ্যায় উল্লিখিত MoHFW ভারতীয় সীমা ব্যবহার করা হয়েছে। WHO আন্তর্জাতিক সীমা আলাদা দেখানো হয়। ব্যক্তিগত সিদ্ধান্তে পেশাজীবীর মূল্যায়ন নিন।"],
      ["১৮ বছরের কম বয়সে ব্যবহার করা যাবে?", "না। শিশু ও কিশোরদের জন্য বয়স অনুযায়ী বৃদ্ধির মূল্যায়ন দরকার, প্রাপ্তবয়স্কদের এই শ্রেণি নয়।"],
      ["বেশি BMI মানেই ডায়াবেটিস বা হৃদ্‌রোগ?", "না। BMI প্রাথমিক যাচাইয়ের মাপ। রক্তচাপ, পরীক্ষা, স্বাস্থ্যের ইতিহাস ও পেশাজীবীর মূল্যায়ন আলাদা তথ্য দেয়।"],
      ["কোমরের মাপ দেওয়া বাধ্যতামূলক?", "না। এটি ছাড়াই BMI হিসাব করতে পারেন। দিলে আলাদা মানদণ্ড দেখানো হয়, রোগ নির্ণয় নয়।"],
    ],
    sources: "চিকিৎসা তথ্যসূত্র", sourceNote: "তথ্যসূত্র যাচাই: ৪ সেপ্টেম্বর ২০২৬। Worklity স্বাধীন; WHO, MoHFW, NHM বা ভারত সরকারের সঙ্গে যুক্ত বা তাদের অনুমোদিত নয়।",
    disclaimer: "এই ক্যালকুলেটর শুধু তথ্য ও স্বাস্থ্য সচেতনতার জন্য। এটি চিকিৎসা পরামর্শ, রোগ নির্ণয় বা চিকিৎসার বিকল্প নয়।",
    errors: { ADULTS_ONLY: "এই ক্যালকুলেটর শুধু ১৮ বছর বা তার বেশি বয়সীদের জন্য। শিশু বা কিশোরদের ক্ষেত্রে প্রাপ্তবয়স্ক BMI শ্রেণি ব্যবহার করবেন না।", INVALID_AGE: "বয়স ১৮ থেকে ১২০-এর মধ্যে পূর্ণ বছরে দিন।", INVALID_SEX: "কোমরের মানদণ্ডের জন্য পুরুষ বা মহিলা বেছে নিন।", INVALID_HEIGHT_UNIT: "cm বা ফুট + ইঞ্চি বেছে নিন।", INVALID_HEIGHT: "উচ্চতা ৫০–২৭৫ cm বা সমান ফুট/ইঞ্চিতে সঠিকভাবে দিন।", INVALID_FEET: "পূর্ণ ফুট ০–৯ দিন; মোট উচ্চতাও সঠিক সীমায় থাকতে হবে।", INVALID_INCHES: "ইঞ্চি ০ থেকে ১২-এর কম দিন; পূর্ণ ফুট হলে ০ দিন।", INVALID_WEIGHT: "সঠিক ওজন ১০–৬৫০ kg-এর মধ্যে দিন।", INVALID_WAIST: "কোমর খালি রাখুন বা ৪০–২৫০ cm-এর মধ্যে সঠিক মাপ দিন।", INVALID_INPUT: "মাপগুলো দেখে সঠিক সংখ্যা দিন।" },
  },
};
