export const COPY = {
  en: {
    eyebrow: "Liver health screening",
    title: "FIB-4 Liver Fibrosis Risk Calculator",
    support: "MASLD / NAFLD",
    intro: "The FIB-4 score uses age, AST, ALT and platelet count to estimate the likelihood of advanced liver fibrosis. This FIB-4 calculator—also searched as a FIB 4 score calculator—is a screening tool, not a diagnosis, and clinical interpretation may require professional review.",
    formTitle: "Enter your values",
    formHint: "Use results from the same blood test. All fields are required.",
    age: "Age",
    ast: "AST",
    alt: "ALT",
    platelets: "Platelet count",
    years: "years",
    calculate: "Calculate FIB-4",
    reset: "Reset",
    plateletHelpStandard: "Enter the full ×10⁹/L value, for example 250—not 2.5.",
    plateletHelpLakh: "Example: 2.5 lakh/µL equals 250 ×10⁹/L.",
    resultTitle: "FIB-4 Score",
    waiting: "Enter valid values and calculate to see your result.",
    summary: "Values used",
    lowerTitle: "Lower FIB-4 risk",
    lowerText: "The score is below the age-appropriate lower threshold. A low result cannot completely exclude significant fibrosis; clinical context still matters.",
    intermediateTitle: "Intermediate FIB-4 risk",
    intermediateText: "Further non-invasive assessment may be appropriate based on clinical evaluation, such as liver elastography (FibroScan) or ELF.",
    higherTitle: "Higher FIB-4 risk",
    higherText: "Discuss this result with a qualified healthcare professional. Further clinical evaluation and non-invasive assessment may be appropriate.",
    limitedTitle: "Limited accuracy below age 35",
    limitedText: "The numerical score is shown, but FIB-4 is less reliable in this age group and should not be used alone for risk stratification. Discuss the clinical context with a qualified healthcare professional.",
    howTitle: "How FIB-4 is calculated",
    howText: "FIB-4 combines age, AST, ALT and platelet count. Platelets are converted to ×10⁹/L before calculation; classification uses the full unrounded score.",
    interpretationTitle: "MASLD / NAFLD interpretation",
    interpretationText: "For ages 35–64, scores below 1.30 are lower risk, 1.30 through 2.67 are intermediate, and scores above 2.67 are higher risk. From age 65, the lower threshold is adjusted to 2.00 while the upper threshold remains 2.67.",
    limitationsTitle: "Important limitations",
    limitations: [
      "FIB-4 is a non-invasive risk-stratification aid, not a diagnosis.",
      "It cannot diagnose or exclude liver fibrosis, cirrhosis or liver disease by itself.",
      "A low result cannot completely exclude significant fibrosis.",
      "Age, other health conditions and the clinical situation can affect interpretation.",
      "FIB-4 is less reliable below age 35.",
      "Acute illness or temporarily, markedly abnormal liver enzymes can make interpretation inappropriate.",
    ],
    faqTitle: "Frequently asked questions",
    faqs: [
      ["What is FIB-4?", "FIB-4 is a calculation using age, AST, ALT and platelet count to help stratify the risk of liver fibrosis."],
      ["Does a low score rule out liver fibrosis?", "No. A low score lowers estimated risk in the intended context but cannot completely exclude significant fibrosis."],
      ["Why is the threshold different from age 65?", "Age affects FIB-4, so MASLD guidance uses a higher lower-risk threshold for older adults."],
      ["What should I do with an intermediate or higher result?", "Discuss it with a qualified healthcare professional, who can decide whether clinical review or a secondary assessment is appropriate."],
    ],
    sourcesTitle: "Sources / References",
    sourcesIntro: "These references support the formula, risk-stratification approach and limitations. They do not endorse Worklity.",
    disclaimer: "This calculator is for informational and health-awareness purposes only. It is not medical advice, diagnosis or treatment and does not replace assessment by a qualified healthcare professional.",
    privacy: "Values entered here remain in this page session and are not saved by this calculator.",
    errors: {
      AGE_INVALID: "Enter a valid age.", AGE_WHOLE_YEARS: "Enter age in completed whole years.", AGE_OUT_OF_RANGE: "This calculator is for adults aged 18–120. Check the age.",
      AST_INVALID: "Enter a valid AST value.", AST_OUT_OF_RANGE: "Check the AST value and unit (U/L).",
      ALT_INVALID: "Enter a valid ALT value.", ALT_OUT_OF_RANGE: "Check the ALT value and unit (U/L).",
      PLATELETCOUNT_INVALID: "Enter a valid platelet count.", PLATELET_INVALID: "Enter a valid platelet count.", PLATELET_UNIT_INVALID: "Choose a platelet unit.", PLATELET_OUT_OF_RANGE: "Check the platelet value and selected unit. Use 250 for ×10⁹/L or 2.5 for lakh/µL.",
      RESULT_INVALID: "A reliable result could not be calculated. Check all values.",
    },
  },
  bn: {
    eyebrow: "লিভার স্বাস্থ্য যাচাই",
    title: "FIB-4 লিভার ফাইব্রোসিস ঝুঁকি ক্যালকুলেটর",
    support: "MASLD / NAFLD",
    intro: "বয়স, AST, ALT ও প্লেটলেট সংখ্যা ব্যবহার করে FIB-4 স্কোর উন্নত লিভার ফাইব্রোসিসের সম্ভাবনার ঝুঁকি-অনুমান দেয়। এটি একটি স্ক্রিনিং টুল, রোগ নির্ণয় নয়; ফলের ক্লিনিক্যাল ব্যাখ্যার জন্য পেশাদার পরামর্শ প্রয়োজন হতে পারে।",
    formTitle: "আপনার মান লিখুন",
    formHint: "একই রক্ত পরীক্ষার রিপোর্টের মান ব্যবহার করুন। সব ঘর পূরণ করা জরুরি।",
    age: "বয়স",
    ast: "AST",
    alt: "ALT",
    platelets: "প্লেটলেট সংখ্যা",
    years: "বছর",
    calculate: "FIB-4 হিসাব করুন",
    reset: "রিসেট",
    plateletHelpStandard: "সম্পূর্ণ ×10⁹/L মান লিখুন—যেমন 250, 2.5 নয়।",
    plateletHelpLakh: "উদাহরণ: 2.5 লাখ/µL = 250 ×10⁹/L।",
    resultTitle: "FIB-4 স্কোর",
    waiting: "সঠিক মান লিখে ফল দেখার জন্য হিসাব করুন।",
    summary: "ব্যবহৃত মান",
    lowerTitle: "কম FIB-4 ঝুঁকি",
    lowerText: "স্কোরটি বয়স অনুযায়ী কম ঝুঁকির সীমার নিচে। তবে কম ফল দিয়েও উল্লেখযোগ্য ফাইব্রোসিস পুরোপুরি বাদ দেওয়া যায় না; ক্লিনিক্যাল পরিস্থিতি গুরুত্বপূর্ণ।",
    intermediateTitle: "মধ্যবর্তী FIB-4 ঝুঁকি",
    intermediateText: "ক্লিনিক্যাল মূল্যায়নের ভিত্তিতে লিভার ইলাস্টোগ্রাফি (FibroScan), ELF বা অন্য উপযুক্ত পরীক্ষা প্রয়োজন হতে পারে।",
    higherTitle: "বেশি FIB-4 ঝুঁকি",
    higherText: "যোগ্য স্বাস্থ্য পেশাজীবীর সঙ্গে ফলটি আলোচনা করুন। আরও ক্লিনিক্যাল মূল্যায়ন বা নন-ইনভেসিভ পরীক্ষা উপযুক্ত হতে পারে।",
    limitedTitle: "৩৫ বছরের কম বয়সে নির্ভুলতা সীমিত",
    limitedText: "সংখ্যাগত স্কোর দেখানো হয়েছে, তবে এই বয়সে FIB-4 কম নির্ভরযোগ্য এবং শুধু এই ফল দিয়ে ঝুঁকি নির্ধারণ করা উচিত নয়। যোগ্য স্বাস্থ্য পেশাজীবীর সঙ্গে ক্লিনিক্যাল পরিস্থিতি আলোচনা করুন।",
    howTitle: "FIB-4 কীভাবে হিসাব হয়",
    howText: "বয়স, AST, ALT ও প্লেটলেট দিয়ে FIB-4 হিসাব করা হয়। হিসাবের আগে প্লেটলেটকে ×10⁹/L-এ রূপান্তর করা হয়; পূর্ণ, রাউন্ড না-করা স্কোর দিয়ে শ্রেণি নির্ধারিত হয়।",
    interpretationTitle: "MASLD / NAFLD ব্যাখ্যা",
    interpretationText: "৩৫–৬৪ বছরে ১.৩০-এর কম কম ঝুঁকি, ১.৩০ থেকে ২.৬৭ মধ্যবর্তী, এবং ২.৬৭-এর বেশি বেশি ঝুঁকি। ৬৫ বছর থেকে কম ঝুঁকির সীমা ২.০০; উপরের সীমা ২.৬৭ থাকে।",
    limitationsTitle: "গুরুত্বপূর্ণ সীমাবদ্ধতা",
    limitations: ["FIB-4 একটি নন-ইনভেসিভ ঝুঁকি-বাছাই সহায়ক, রোগ নির্ণয় নয়।", "এটি একা লিভার ফাইব্রোসিস, সিরোসিস বা লিভারের রোগ নিশ্চিত বা বাদ দিতে পারে না।", "কম ফলেও উল্লেখযোগ্য ফাইব্রোসিস পুরোপুরি বাদ যায় না।", "বয়স, অন্য স্বাস্থ্য সমস্যা ও ক্লিনিক্যাল পরিস্থিতি ফলের ব্যাখ্যাকে প্রভাবিত করতে পারে।", "৩৫ বছরের কম বয়সে FIB-4 কম নির্ভরযোগ্য।", "তীব্র অসুস্থতা বা সাময়িকভাবে খুব অস্বাভাবিক লিভার এনজাইম থাকলে ফল ব্যাখ্যা উপযুক্ত নাও হতে পারে।"],
    faqTitle: "সাধারণ প্রশ্ন",
    faqs: [["FIB-4 কী?", "বয়স, AST, ALT ও প্লেটলেট দিয়ে লিভার ফাইব্রোসিসের ঝুঁকি বাছাইয়ে সহায়ক একটি হিসাব।"], ["কম স্কোর কি ফাইব্রোসিস পুরোপুরি বাদ দেয়?", "না। নির্দিষ্ট পরিস্থিতিতে ঝুঁকি কম বোঝালেও উল্লেখযোগ্য ফাইব্রোসিস পুরোপুরি বাদ দেয় না।"], ["৬৫ বছর থেকে সীমা আলাদা কেন?", "বয়স FIB-4-কে প্রভাবিত করে, তাই MASLD নির্দেশনায় বয়স্কদের জন্য কম-ঝুঁকির সীমা বেশি।"], ["মধ্যবর্তী বা বেশি ফল হলে কী করব?", "যোগ্য স্বাস্থ্য পেশাজীবীর সঙ্গে আলোচনা করুন। তিনি ক্লিনিক্যাল পর্যালোচনা বা পরবর্তী পরীক্ষা দরকার কি না ঠিক করবেন।"]],
    sourcesTitle: "তথ্যসূত্র",
    sourcesIntro: "এই সূত্রগুলো হিসাব, ঝুঁকি-বাছাই ও সীমাবদ্ধতার ভিত্তি। তারা Worklity-কে অনুমোদন করে না।",
    disclaimer: "এই ক্যালকুলেটর শুধু তথ্য ও স্বাস্থ্য সচেতনতার জন্য। এটি চিকিৎসা পরামর্শ, রোগ নির্ণয় বা চিকিৎসা নয় এবং যোগ্য স্বাস্থ্য পেশাজীবীর মূল্যায়নের বিকল্প নয়।",
    privacy: "এখানে দেওয়া মান বর্তমান পেজ সেশনেই থাকে; এই ক্যালকুলেটর তা সংরক্ষণ করে না।",
    errors: {
      AGE_INVALID: "সঠিক বয়স লিখুন।", AGE_WHOLE_YEARS: "সম্পূর্ণ বছরে বয়স লিখুন।", AGE_OUT_OF_RANGE: "এই ক্যালকুলেটর ১৮–১২০ বছর বয়সী প্রাপ্তবয়স্কদের জন্য। বয়স যাচাই করুন।",
      AST_INVALID: "সঠিক AST মান লিখুন।", AST_OUT_OF_RANGE: "AST মান ও একক (U/L) যাচাই করুন।", ALT_INVALID: "সঠিক ALT মান লিখুন।", ALT_OUT_OF_RANGE: "ALT মান ও একক (U/L) যাচাই করুন।",
      PLATELETCOUNT_INVALID: "সঠিক প্লেটলেট সংখ্যা লিখুন।", PLATELET_INVALID: "সঠিক প্লেটলেট সংখ্যা লিখুন।", PLATELET_UNIT_INVALID: "প্লেটলেটের একক বেছে নিন।", PLATELET_OUT_OF_RANGE: "প্লেটলেট মান ও নির্বাচিত একক যাচাই করুন। ×10⁹/L হলে 250 বা লাখ/µL হলে 2.5 লিখুন।", RESULT_INVALID: "নির্ভরযোগ্য ফল হিসাব করা যায়নি। সব মান যাচাই করুন।",
    },
  },
};

export const SOURCES = [
  { label: "AASLD — Noninvasive Assessment of Patients with MASLD", href: "https://www.aasld.org/liver-fellow-network/core-series/clinical-pearls/spare-me-jab-noninvasive-assessment-patients-masld" },
  { label: "AASLD — Practice Guidance on NAFLD clinical assessment", href: "https://journals.lww.com/hep/fulltext/2023/05000/aasld_practice_guidance_on_the_clinical.31.aspx" },
  { label: "EASL–EASD–EASO — MASLD Clinical Practice Guidelines", href: "https://easl.eu/publication/easl-easd-easo-clinical-practice-guidelines-managment-of-metabolic-dysfunction-associated-steatotic-liver-disease/" },
];
